package io.protonull.template;

import vg.civcraft.mc.civmodcore.ACivMod;
import vg.civcraft.mc.civmodcore.command.StandaloneCommandHandler;

/**
 * <p>This is an example plugin.</p>
 *
 * <p>Make sure that this class' class path is represented correctly in the plugin.yml. It's generated by default
 * through the concatenation of your groupId, artifactId, name, and a plugin suffix. If you'd prefer a different
 * setup, then change it there but make sure to maintain it.</p>
 */
public final class TemplatePlugin extends ACivMod {

	/**
	 * <p>The enable process of this plugin.</p>
	 *
	 * <p>If you do not wish to use {@link StandaloneCommandHandler} for your commands then you should use the
	 * following prior to super.onEnable(): {@code this.useNewCommandHandler = false;}</p>
	 */
	@Override
	public void onEnable() {
		// Call CivModCore's enable process, this should be called first before you've done anything else
		super.onEnable();
	}

	@Override
	public void onDisable() {
		// Call CivModCore's disable process, this should be called last after you've done everything else
		super.onDisable();
	}

}
